import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./components/CartContext";
import { Toaster } from "sonner";
import Logo from "./components/Logo";
import MainMenu from "./components/BeautifulMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Manaro - By Prakash Tauro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center gap-10 p-6 bg-white shadow-md">
          <div className="text-2xl font-bold text-indigo-600 cursor-pointer">
            <Logo />

          </div>
          {/* <nav className="space-x-8 text-gray-700 font-semibold">
            <a href="/" className="hover:text-indigo-600 transition">Home</a>
            <a href="/products" className="hover:text-indigo-600 transition">Products</a>
            <a href="#about" className="hover:text-indigo-600 transition">About</a>
            <a href="#contact" className="hover:text-indigo-600 transition">Contact</a>
          </nav> */}
          <MainMenu />
        </header>

        <span className="absolute right-5 p-2 rounded-lg text-xs top-5  tr,ansform -translate-y-1/2 text-white bg-red-700 font-bold">
          Site is under construction
        </span>
        <CartProvider>
          {children}
          <Toaster richColors position="top-center" duration={2000} />
        </CartProvider>
      </body>
    </html>
  );
}
