import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./components/CartContext";
import { Toaster } from "sonner";
import Logo from "./components/Logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Manaro - By Prakash Tauro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Logo />

        <span className="absolute right-5 p-2 rounded-lg text-xs top-5  tr,ansform -translate-y-1/2 text-white bg-red-700 font-bold">
          Site is under construction
        </span>
        <CartProvider>
          {children}
          <Toaster richColors position="top-center" duration={2000}  />
        </CartProvider>
      </body>
    </html>
  );
}
